services:
  ### Prefect Orion API
  orion:
    container_name: orion
    image: prefecthq/prefect:2.7.7-python3.11
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_API_URL= http://host.docker.internal:4200/api
      - PREFECT_ORION_API_HOST= 0.0.0.0
    ports:
      - 4200:4200
    profiles: ["orion"]

  ### Prefect CLI
  cli:
    container_name: cli
    image: prefecthq/prefect:2.7.7-python3.11
    entrypoint: ./docker-entrypoint.sh
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
      - "~/.google/credentials/google_credentials.json:/root/secrets"
    profiles: ["cli"]
  
  dbt:
    build:
      context: .
    volumes:
      - .:/usr/app/dbt
      - ~/.dbt/:/root/.dbt/
      - "~/.google/credentials/google_credentials.json:/root/secrets/gcp_credentials.json"
    working_dir: /usr/app/dbt/
    profiles: ["dbt"]
      
volumes:
  prefect:
